# Generated by Django 4.1.2 on 2022-10-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_carmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="color",
            field=models.CharField(
                choices=[(1, "yellow"), (2, "blue"), (3, "gray")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="type",
            field=models.CharField(
                choices=[(1, "hatch"), (2, "sedan"), (3, "convertible")], max_length=255
            ),
        ),
        migrations.DeleteModel(
            name="CarColorModel",
        ),
        migrations.DeleteModel(
            name="CarTypeModel",
        ),
    ]
