# Generated by Django 4.1.2 on 2022-10-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
        ("cars", "0003_alter_carmodel_color_alter_carmodel_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carmodel",
            options={"verbose_name_plural": "Cars"},
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="persons.personmodel",
            ),
        ),
    ]
